### ISSUE TITLE
Read multiple registers in one call

### ISSUE THREAD

**Issue by sergiupienar** [hsocarras/nodbus-plus#1]
Is it possible to read multiple holding registers in a single call ?

```
i.e. modbusSTCPClient.ReadHoldingRegisters(1, 8000, 1);
followed by modbusSTCPClient.ReadHoldingRegisters(1, 9000, 1);
```

From what I see if I do the above I only get a 'raw_data' event being emmited for the first read register - 8000.

**Comment by hsocarras** [comment]
There are an example. The following code:

      //reading 1 register
      modbusSTCPClient.ReadHoldingRegisters(1, 0, 1);
      //reading 5 registers
      modbusSTCPClient.ReadHoldingRegisters(1, 10, 5);
get:

    starting test
    <Buffer 01 03 02 00 3b f9 97>
    Map { '4x0' => <Buffer 00 3b> }

You only get the raw event and data event for the first indication. 
It's because the client must wait for a slave response or timeout event for do a new indication.
The following code works fine.

     setTimeout(function(){
      //reading 1 register
      modbusSTCPClient.ReadHoldingRegisters(1, 0, 1);
      },50);

      setTimeout(function(){
      //reading 5 registers
      modbusSTCPClient.ReadHoldingRegisters(1, 10, 5);
      },150);

**Comment by hsocarras** [comment]
You can also add a new listener for data event.

    modbusSTCPClient.ReadHoldingRegisters(1, 0, 1);
    modbusSTCPClient.once('data', function(){
    modbusSTCPClient.ReadHoldingRegisters(1, 10, 5);
    })

**Comment by hsocarras** [comment]
I've been reading modbus tcp specification and should be possible to do what you want.

"Normally, on MODBUS serial line a client must send one request at a time. This means 
that the client must wait for the answer to the first request before sending a second 
request. On TCP/MODBUS, several requests can be sent without waiting for a 
confirmation to the same server."

I will implement this feature and a "busy" event in next release. 

Thanks for using this library.

**Comment by sergiupienar** [comment]
Hi,

Nevermind, I implemented an event called 'new_available_request' in the modbus_master.js .
This way, I`m notified when the currentModbusRequest has finished processing and I'm able to issue a new request.

Works fine for my intended usecase - asking the value of certain registers in one call.

The implmentation I'm using is RTU over TCP/IP.

**Comment by hsocarras** [comment]
Ok, I will fixed anyway in the next release.
Thanks.

2018-02-12 13:23 GMT+00:00 sergiupienar <notifications@github.com>:
