### ISSUE TITLE
can udp supported?

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [hsocarras/nodbus-plus#2]
can udp and rtu/ascii over udp supported?
can serial port over supported? seems like /dev/ttyUSB0?

thanks to your great work, api is so easy to understand

**Comment by hsocarras** [comment]
Sorry, at this moment udp is not soported. it will be done on next release. Right now I'm working on TCP coalescing support (see Issue 1)
Support for a serial interface also are intended, but at this time I have problem with testing node serialport package.
